---
- name: Update Rocky Linux servers
  hosts: rockylinux_servers
  become: yes

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
        update_cache: yes

    - name: Perform system upgrade
      package:
        name: "*"
        state: latest
        update_cache: yes
        allow_downgrade: no
        
    - name: Perform DNF autoremove
      ansible.legacy.dnf:
        autoremove: yes

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
